[build]
command = "bun run --cwd apps/marketing build"
ignore = "bun scripts/netlify-ignore-build.ts marketing"
publish = "/apps/marketing/.next"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "false"
