[build]
command = "bun run --cwd apps/marketing build"
ignore = "node ./scripts/netlify-ignore-build.mjs marketing"
publish = "/apps/marketing/.next"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "false"
